сделал ветку go-issue-1
Tazya/kolesa-upgrade-news-bot pull request #1
Opened 2022-11-10 20:37 UTC by FishSev

1) можно сразу запускать в контейнере через "bash build_and_run.sh" 
2) немного подправил Dockerfile

2022-11-11 11:31 UTC, Tazya requested changes

2022-11-11 11:31 UTC, Tazya commented on _help.txt
> +Сгененрировать ключ и добавить его на сервер
Давай лучше в README.md
Markdown слишком хорош, чтобы от него отказываться

2022-11-11 11:31 UTC, Tazya commented on _help.txt
> +ssh-copy-id -i ~/.ssh/id_rsa.pub root@176.57.69.55
Давай эту инструкцию где-нибудь внутри группы хранить. Она касется очень частного кейса деплоя сервиса, а не самого кода сервиса.

2022-11-11 11:31 UTC, Tazya commented on _help.txt
> +docker stop $(docker ps -a -q)
Что если у меня куча процессов в докере? Лучше не юзать настолько динамично

2022-11-11 11:31 UTC, Tazya commented on build_and_run.sh
> +docker build -t hello:v1 .
лучше вынеси в Makefile, будет проще использовать

2022-11-11 11:31 UTC, Tazya commented on main.go
> +	fileBytes, err := ioutil.ReadFile("Hello.jpg")
ioutil.ReadFile - deprecated
`os.ReadFile` - быстрее и рекомендуется разработчиками Go

2022-11-11 11:31 UTC, Tazya commented on main.go
> +func handleRequest_health(w http.ResponseWriter, r *http.Request) {
Хендлеры лучше перенести в отдельный пакет. Разжиреет main сильно.

какая-нибудь директория `http/handlers` и пакет `handlers`

2022-11-11 11:31 UTC, Tazya commented on main.go
> +	resp["status"] = "ok"
Можно упростить
```go
resp := map[string]string{
    "status": "ok",
}
```

2022-11-11 21:48 UTC, FishSev commented on _help.txt
> +Сгененрировать ключ и добавить его на сервер
это технические рекомендации для меня, я их вообще убрал

2022-11-11 21:48 UTC, FishSev commented on _help.txt
> +ssh-copy-id -i ~/.ssh/id_rsa.pub root@176.57.69.55
я все их сохраню, потом если надо выложу куда-нибудь

2022-11-11 21:48 UTC, FishSev commented on _help.txt
> +docker stop $(docker ps -a -q)
+

2022-11-11 21:49 UTC, FishSev commented on build_and_run.sh
> +docker build -t hello:v1 .
вынес

2022-11-11 21:49 UTC, FishSev commented on main.go
> +	fileBytes, err := ioutil.ReadFile("Hello.jpg")
исправил

2022-11-11 21:49 UTC, FishSev commented on main.go
> +func handleRequest_health(w http.ResponseWriter, r *http.Request) {
вынес

2022-11-11 21:49 UTC, FishSev commented on main.go
> +	resp["status"] = "ok"
поменял

2022-11-12 16:02 UTC, Tazya approved these changes

2022-11-12 16:02 UTC, Tazya commented on Dockerfile
> +CMD /usr/local/bin/app --port $PORT
В итоге порт не юзается. Можешь сделать структуру конфига, в которой будет свойство port и этот конфиг передать в инициализацию сервера?

2022-11-13 06:08 UTC, Tazya requested changes
Работа с конфигами выстроена не очень оптимально.

Давай так:
1. В main функции создаешь и заполняешь структуру конфига (назови её `config.Config` и добавь свойство `Port string`. Больше нигде в коде не нужно менять поля этой структры.
2. Прокидываешь конфиг через все аргументы вплоть до `InitServer(cfg config.Config)`
3. И тут уже пользуешься свойством `cfg.Port`

Так ты получишь инициализацию конфига в самом начале и проброс дальше в место, где инициализируется http сервер.

Так мы отделим побочные эффекты(поход в файл) от логики

2022-11-14 12:21 UTC, Tazya requested changes

2022-11-14 12:21 UTC, Tazya commented on internal/server/setPort.go
> +package server
переусложнение

Просто сделать как-то так в main файле

```go
	port := flag.String("port", "8888", "HTTP port")
	flag.Parse()
```
переменная `port`, будет содержать ссылку на адрес памяти в котором будет храниться порт. И вот его уже закинь в конфиг

2022-11-14 14:46 UTC, merged